### ISSUE TITLE
Population Characteristics: Compare populations (add more charts in config file)

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/catalogue#747] opened 2014-12-03 02:55 UTC
Add in the configuration file to show more characteristics.

Also, the feature are hidden and show be shown (to dev version)

**Comment by ribeiroct** [comment] 2015-02-23 20:43
Active Patients, follow-up time(patient time ?) were already implemented.

Meanwhile i implemented the missing year of birth and start year charts.

The number of patients is missing. The data isnt on the samples of jerboa i looked at, maybe it can be calculated from the sommatory of "start year" 

I think the aggregator is returning bad values(at least it looks that way to me).

**Comment by bastiao** [comment] 2015-02-23 21:54
@ribeiroct is it already fixed?

I checked the Active patients and it looks fine in the aggregator. Comparison with 3 databases at same time.

Also, one thing that I did not implement in the aggregator is the hook to re-aggregate when something change in one databases. we may need for a async processo to recalculate all things. 
Maybe we can think about a scalable matter, but at the moment, we need to finish it and starting pushing the integration with Achilles.

**Comment by ribeiroct** [comment] 2015-02-24 11:05
No i couldn't find the problem, it only happens on category counting, so active patients is fine. Im making the pull request so it doesnt get forgotten.

**Comment by ribeiroct** [comment] 2015-09-20 11:11
@bastiao : Can we close this ? This is kind of a duplicate of #838 . And we are already waiting for feedback on that issue, so no need for this one to be open

**Closed by ribeiroct** 2015-09-20 11:11 UTC
Labels: enhancement
